#pragma once

#undef TAPPING_TERM
#define TAPPING_TERM 150
#define RETRO_TAPPING

#undef TAPPING_TOGGLE
#define TAPPING_TOGGLE 2

#define MK_3_SPEED
#define MK_MOMENTARY_ACCEL

// This is ROW*MATRIX_COLS + COL
#define CAPS_LOCATION (MATRIX_COLS * 0 + 0)
