#pragma once

#undef TAPPING_TERM
#define TAPPING_TERM 225

#undef TAPPING_TOGGLE
#define TAPPING_TOGGLE 2

#define RETRO_TAPPING
#define DUMMY_MOD_NEUTRALIZER_KEYCODE KC_RCTL

#define MK_3_SPEED
#define MK_MOMENTARY_ACCEL

#define CAPS_LOCATION (MATRIX_COLS * 0 + 0)

#define IDLE_PROFILE_INDEX 0

